### ISSUE TITLE
optional Zeitzone / UTC offset mit speichern 

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/yform_geo_osm#13]
Ich bräuchte anhand der Location / lat/lng die passende Zeitzone oder weitere Metadaten (Staat). Lässt sich dieses in yform_geo_osm implementieren?

**Comment by skerbis** [comment]
https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=7124131943&class=office
Das ist was man aktuell einlesen könnte

**Comment by AWqxKAWERbXo** [comment]
Wie müsste das aussehen, dass ich diese Daten optional in Inputfelder übernehmen kann? Geht das evtl. bereits?

**Comment by AWqxKAWERbXo** [comment]
Wobei ich diesen Key da auch nicht in den Relationen finde:
https://wiki.openstreetmap.org/wiki/Key:timezone

Laut Wiki sollte es ihn geben.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/yform_geo_osm/blob/5794b5c26b020fec582ff88904f9e7059c5c9ab3/assets/geo_osm.js#L98 

Check mal was das JSON liefert.

**Comment by AWqxKAWERbXo** [comment]
```
[{"place_id":102179201,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":69304922,"boundingbox":["49.1619707","49.1621191","9.2290627","9.229292"],"lat":"49.16204485","lon":"9.229177342710774","display_name":"40, Mettelbachstraße, Salzwerk, Neckarbogen, Heilbronn, Baden-Württemberg, 74076, Deutschland","class":"building","type":"yes","importance":0.42099999999999993}]
```

Döööööööd :(

die Timezone hängt ja an den Grenzen eines Staats oder einer Staatengemeinschaft. deswegen würde man die Daten evtl. bei Deutschland oder Bawü finden in diesem Beispiel.

**Comment by AWqxKAWERbXo** [comment]
(funktioniert aber auch nicht)

https://nominatim.openstreetmap.org/search?state=Baden-W%C3%BCrttemberg&format=json&polygon=0&addressdetails=1&limit=1

**Comment by AWqxKAWERbXo** [comment]
https://trac.openstreetmap.org/ticket/4200

danke fürs Mitlesen...
