### ISSUE TITLE
Rückwärtssuche: Location suchen und in Straße/ZIP/City/Country-Felder eintragen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/yform_geo_osm#14]

**Comment by NGWNGW** [comment]
Für die Geokodierung eines einzelnen Datensatzes wird aktuell Nominatim genutzt. Dieser Dienst unterstützt auch Reverse-Geocoding... sollte also machbar sein https://nominatim.org/release-docs/develop/api/Reverse/

**Comment by AWqxKAWERbXo** [comment]
Aktuell ist es wohl geoapify und auch die unterstützen das
