### ISSUE TITLE
karte wird nicht angezeigt - JS error

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/yform_geo_osm#16]
Hab das addon yform_geo_osm 1.2.3 in Redaxo 5.11.0 mit yform 3.4.1 installiert. Aber im Backend wird keine Karte angezeigt. API Key hab ich eingetragen - es kommt diese Fehlermeldung:
![error_geo_osm](https://user-images.githubusercontent.com/3844106/92451976-ba9a2a80-f1bd-11ea-88dc-2221aa68712f.gif)

**Comment by skerbis** [comment]
Was für ein API-Code?

**Comment by steri-rex** [comment]
Wie ist das gemeint? Ich hab mich bei geoapify registriert und einen API Key erstellt - diesen dann im Addon eingetragen.

**Comment by steri-rex** [comment]
es hat tatsächlich was gefehlt - ich hatte die Felder für LAT und LNG in der Tabelle noch nicht angelegt - nun funktionierte es
