### ISSUE TITLE
Problem mit yform4

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/yform_geo_osm#18]
Hier:
https://github.com/FriendsOfREDAXO/yform_geo_osm/blob/1d7285fdc84cb1227f77c6cdd72933881135dfe1/lib/yform_value_osm_geocode.php#L13
Wird 'value.osm_geocode.tpl.php' als Templage übergeben. wenn ich das richtig sehe, gibts die Datei hier gar nicht und Redaxo wirft ein Whoops "Path connot be empty"

**Comment by skerbis** [comment]
@marcohanke ist das bei dir in der aktuellen yform4 beta immer noch so? 
Bitte mal meinen PR testen der behebt ein anderes Problem, aber deins tritt dabei bei mir nicht auf.

**Comment by marcohanke** [comment]
Moin, tut mir leid, ich weiß gerade gar nicht mehr, welches Projekt das war und hab den Usecase nicht mehr vor Augen. Komme leider mindestens diese Woche auch zu nichts mehr ;-)

**Comment by AWqxKAWERbXo** [comment]
Kann ich bestätigen

<html>
<body>


11.12.2021, 15:25:40 | Warning | yform template value.osm_geocode.tpl.php not found | redaxo/src/addons/yform/lib/yform.php | 535
-- | -- | -- | -- | --


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by skerbis** [comment]
@alxndr-w  wann taucht dieser Fehler auf. Habe es gerade in einer aktuellen Installation um Einsatz und erhalte diese Warning nicht (Debug-Mode ist eingeschaltet)

**Comment by skerbis** [comment]
scheint das Gleiche zu sein: https://github.com/FriendsOfREDAXO/yform_spam_protection/issues/50

**Comment by AWqxKAWERbXo** [comment]
Erhalte diese Meldung auch nicht mehr.
