### ISSUE TITLE
Verwendung an anderer Stelle

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_geo_osm#2]
Was ist zu tun, damit andere AddOns dieses AddOn verwenden können? z.B. forcal, Meta

**Comment by christophboecker** [comment]
Was hältst Du von der Idee, YFORM-Tabellen und Formulare statt dessen im eigenen Addon einzusetzen?  

<img width="1168" alt="grafik" src="https://user-images.githubusercontent.com/10065904/36799385-5eb17558-1cad-11e8-8fa2-afb3935c9767.png">

<img width="920" alt="grafik" src="https://user-images.githubusercontent.com/10065904/36799454-84fec7d8-1cad-11e8-8b7b-7258521b2cfc.png">

Das ist jetzt mal auf die Schnelle per Workaround entstanden .... 100% schön ist es auch nicht. Aber wenn es nativ von YForm unerstützt werden würde, wäre es eine klasse Sache für viele Addons. oder?

**Comment by skerbis** [comment]
Ja auch nett, aber es geht um die allgemeine Bereitstellung auch abseits von Tabellen

**Comment by christophboecker** [comment]
Ja, verstehe was Du meinst. Ideal wäre eine Art "Feldstandard" für Module, Metadaten, YForm, rex_form. Einmal definiert, überall einsetzbar.

**Comment by skerbis** [comment]
Japp

**Comment by AWqxKAWERbXo** [comment]
Hätte hier auch nochmal Interesse für den Import neuer Locations aus einer ics-Datei. 

Da müsste es einen Modus geben, in dem ich Lat/Lng nur anhand eines Textstrings erkennen kann, da ics-Dateien kein fest definiertes Format für Adressdaten besitzen.

**Comment by AWqxKAWERbXo** [comment]
Completed oder "not planned" @skerbis ?

**Comment by skerbis** [comment]
Kommt .. vielleicht noch heute
