### ISSUE TITLE
yform template value.osm_geocode.tpl.php not found

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_geo_osm#21]
<html>
<body>

11.12.2021, 15:25:40 | Warning | yform template value.osm_geocode.tpl.php not found | redaxo/src/addons/yform/lib/yform.php | 535
-- | -- | -- | -- | --

<br class="Apple-interchange-newline">
</body>
</html>

<details>
<summary>System report (REDAXO 5.13.1, PHP 7.4.25, MariaDB 10.3.32)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.25     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.3.32 |
| Character set | utf8            |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |                     |
| ------------: | :------------------ |
|       Browser | Chrome/96.0.4664.55 |
|      Protocol | HTTP/2.0            |
|         HTTPS | yes                 |

| Packages                    |             |
| --------------------------: | :---------- |
|                accessdenied | 1.0.6       |
|                     adminer | 1.9.2       |
|                      backup | 2.8.0       |
|                 be_password | 2.0.0       |
|                    be_style | 3.0.0       |
|         be_style/customizer | 3.0.0       |
|             be_style/redaxo | 3.0.0       |
|             be_style_fluent | 3.0.2       |
|                     bloecks | 3.1.1       |
|            bloecks/cutncopy | 3.1.1       |
|                cache_warmup | 3.7.0       |
|             consent_manager | 3.0.3       |
|                     cronjob | 2.8.1       |
|                   developer | 3.9.0       |
|                       dsgvo | 0.9beta5    |
|                      events | 2.0.0-beta2 |
|                       feeds | 3.1         |
|                     install | 2.9.3       |
|                 maintenance | 2.6.4       |
|                    markitup | 3.7.1       |
|      markitup/documentation | 1.1.0       |
|                      mblock | 3.4.4       |
|               media_manager | 2.12.1      |
|                   mediapool | 2.11.1      |
|                    metainfo | 2.8.3       |
|                       mform | 6.1.1       |
|                      minify | 2.2         |
|                      pdfout | 4.1.2       |
|                   phpmailer | 2.11.1      |
|                  pixelfirma | 2.1.2       |
|         pixelfirma/px_admin | 2.0         |
|           pixelfirma/px_lib | 2.1         |
|                     project | dev         |
|            quick_navigation | 5.2.1       |
|                   redactor2 | 4.2.1       |
|                   structure | 2.13.1      |
|           structure/content | 2.13.1      |
|           structure/history | 2.13.0      |
|               treestructure | 1.0.3 beta  |
|                    uploader | 2.3.0       |
|                         url | 1.0.1       |
|                 usage_check | 2.3         |
|                       users | 2.8.2       |
|                      watson | 2.2.0       |
|               xoutputfilter | 3.0.0-beta1 |
|       xoutputfilter/backend | 3.0.0       |
| xoutputfilter/documentation | 1.0.0       |
|      xoutputfilter/frontend | 3.0.0       |
| xoutputfilter/import_export | 3.0.0       |
|     xoutputfilter/languages | 3.0.0       |
|                       yform | 4.0.0-beta4 |
|                 yform/email | 4.0.0-beta4 |
|               yform/manager | 4.0.0-beta4 |
|                 yform/tools | 4.0.0-beta4 |
|               yform_geo_osm | 1.2.4       |
|       yform_spam_protection | 1.1.0       |
|             yform_usability | 1.4         |
|                    yrewrite | 2.8.2       |
|                 zip_install | 1.1         |

</details>

**Comment by AWqxKAWERbXo** [comment]
bereits in #18 gemeldet
