### ISSUE TITLE
Auflösung via https://nominatim.openstreetmap.org/search?q=

### ISSUE THREAD

**Issue by thielpeter** [FriendsOfREDAXO/yform_geo_osm#23]
https://github.com/FriendsOfREDAXO/yform_geo_osm/blame/master/assets/geo_osm.js#L98

Adressauflösung via https://nominatim.openstreetmap.org/search?street=Stabenhof%202&city=Brodenbach&postalcode=56332&format=json&polygon=0&addressdetails=0&limit=1 funktioniert nicht.

Vorschlag: Auflösung via 

```xhr.open('GET','https://nominatim.openstreetmap.org/search?q='+street+' '+city+' '+postalcode+'&format=json&polygon=0&addressdetails=0&limit=1');```

**Comment by AWqxKAWERbXo** [comment]
Hey @thielpeter , du kannst Code mit 3 Backticks markieren, dann wird er im Issue auch so dargestellt wie Code und bleibt nachvollziehbar.

**Comment by thielpeter** [comment]
Danke @alxndr-w

**Comment by skerbis** [comment]
Erledigt
