### ISSUE TITLE
Umstellung auf Namespace

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_geo_osm#28]
**Feature description / Feature Beschreibung**

**Comment by AWqxKAWERbXo** [comment]
Würde ich übernehmen

**Comment by AWqxKAWERbXo** [comment]
@skerbis @christophboecker gibt's noch Dinge abzuwarten, die ihr erstmal in den 1.x-Zweig integrieren möchtet?

Oder kann ich zeitnah loslegen?

**Comment by christophboecker** [comment]
Wann ich was einbringe ist mir relativ egal. 

Ich bin ziemlich weit mit der Validierung der Eingaben in der YForm-Feldkonfiguration (gibt es heute ja noch gar nicht, siehe #32). Den PR könnte ich morgen fertig bekommen. Dann sollte man auch mal die Elemente etwas aufräumen. Die Label beinhalten ja sowohl den Element-Namen wie auch Erklärungen zum Element. Die gehören eigentlich in eine "notice" zum Eingabefeld. Das wäre - um nicht zu viele Themen zu vermischen - der nächste PR. 

Aber das muss Thomas @skerbis entscheiden. Für mich macht es keinen nennenswerten Unterschied, ob ich das vor oder nach Namespace-Umstellung angehe. Vieleicht ist es danach bzw. im selben Release besser aufgehoben, weil sich die Optik doch merklich ändert.

**Comment by skerbis** [comment]
ok gerne erst namespace und dann die validierung. Wir können alles zusammen dann als 2.0 releasen, die 1.4 lassen wir aus

**Comment by skerbis** [comment]
Danke für Euren Einsatz @alxndr-w @christophboecker

**Comment by christophboecker** [comment]
Und der Code könnte bei der Gelegenheit auch modernisiert werden. PHP-CS-FIXER und RexStan, moderne Schreibweisen, usw.

**Comment by christophboecker** [comment]
Und die Texte in die .lang-Dateien schreiben

**Comment by skerbis** [comment]
Hey. Ich wollte erstmal nur einen Wunsch erfüllen. Aber cool wenn wir es modernisieren.

**Comment by christophboecker** [comment]
> Oder kann ich zeitnah loslegen?

Gib mir einfach nen Ping, wenn Du fertig bist.

**Comment by skerbis** [comment]
@alxndr-w du hast **ping** vergessen @christophboecker  😉

**Comment by AWqxKAWERbXo** [comment]
Er war doch im PR mit drin. Aber gut.

Geht auch ein Bing? <https://www.youtube.com/watch?v=pgwr9r36zIU>

**Comment by christophboecker** [comment]
ein Bing, mit einem B wie Paula. ha joh.
