### ISSUE TITLE
Deutscher Tile-Server und Korrekturen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_geo_osm#3]
ich habe den den deutschen TIle-Server eingebunden und unnötige Dateien entfernt
@NGWNGW

**Comment by skerbis** [comment]
@NGWNGW bist du noch Lead des AddOns?

**Comment by NGWNGW** [comment]
Danke für dein Update!

Ja, ich bin hier noch Lead des AddOns.

**Comment by skerbis** [comment]
@NGWNGW meinst du man könnte es für einen allgemeinen Einsatz fit machen?
Also außerhalb von yform?
