### ISSUE TITLE
Aktueller FOR-Lead 

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/yform_geo_osm#35]
Ich habe eben beim Aktualisieren der README gesehen, dass @NGWNGW Lead ist. Ist das noch aktuell?

**Comment by skerbis** [comment]
Auf FOR setzen, schlage ich vor. Ich will‘s nicht sein

**Comment by AWqxKAWERbXo** [comment]
Du @skerbis und @christophboecker dürfen mich gerne zum Lead küren - ich möchte eigentlich nur, dass jemand sowohl bei Verschlimmbesserungen und bei Verbesserungen schnell intervenieren kann und keine PRs liegenbleiben. 

Insb. mit den schlechten Erfahrungen bei ungeklärten Leads und nicht abgesprochenen Commits ist es mir lieber, dass es eine Person gibt, die sich verantwortlich fühlt.

Im Großen und Ganzen ist das Addon ja etabliert und der Zweck gut abgesteckt.

**Comment by NGWNGW** [comment]
Setzt es gerne auf FOR, oder übernehme du direkt @alxndr-w.

**Comment by skerbis** [comment]
Habe @alxndr-w eingetragen. Danke

**Comment by christophboecker** [comment]
Dann können wir das Issue ja schließen. Danke.
