### ISSUE TITLE
Reihenfolge der Adressfelder unwirksam?

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/yform_geo_osm#6]
Könnte es sein, dass im Template `value.osm_geocode.tpl.php` 
https://github.com/FriendsOfREDAXO/yform_geo_osm/blob/03d703316d9b0c4aa98c0e308f7a75ff2566ed4a/ytemplates/bootstrap/value.osm_geocode.tpl.php#L8-L12 ein kleiner gemeiner Bug lauert?

Es will mir einfach nicht gelingen, die Adressfelder zu einer auswertbaren Adresse zu verknüpfen. In der Feld-Parametrisierung müssen die Felder für Strasse, Plz und Ort in genau dieser Reihenfolge angegeben werden. Wenn die Felder in der Tabelle zufällig in genau dieser Reihenfolge stehen, ist die Welt in Ordnung. Sind die Tabellenfelder aber in der Reihenfolge PLZ, Ort, Straße interessiert das das Addon nicht und die Adressauswertung schlägt fehl.

Bin ich der erste, der außer dem Autor das Addon nutzen will, und eine abweichende feldreihenfolge hat? 

Fehlerursache: Die Liste der Tabellenfelder wird in deren Reihenfolge durchlaufen. Da nur geprüft wird, ob der Feldname in der Adressfeldliste ist, nicht aber an welcher Position, werden die Felder stets in der tabellenbezogenen Reihenfolge an das JS übermittelt. 

Helfen würde so etwas:
```
    $adressHelper = array_flip ( $addressfields );
	foreach($this->params["values"] as $val) {
	    if (in_array($val->getName(), $addressfields)) {
	        $address_selectors[$adressHelper[$val->getName()]] = "#".$val->getFieldId();
	    }
	}
    ksort( $address_selectors );
```

Bitte mal drüberschauen. Ich mache erst mal noch keinen PR daraus, weil mir die ganze Adressauflösung von OSM suspekt ist. Da muss ich auch noch mal schauen.

**Comment by KnudH** [comment]
Genau darüber bin ich auch gerade gestolpert! Ich dachte schon ich bin zu blöd. 

@NGWNGW du hast dir den Issue im August zugewiesen, arbeitest du noch daran?

**Comment by NGWNGW** [comment]
@LyR33x , ja, es folgt in den nächsten Tagen ein Release welches dieses Issue beseitigt hat (ist bereits umgesetzt, muss die Sache nur noch hochladen)... sorry für die Verzögerung.

**Comment by NGWNGW** [comment]
Ist nun angepasst.

**Comment by christophboecker** [comment]
Dobsche
