### ISSUE TITLE
Batch-Codieren

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/yform_geo_osm#8]
Wo finde ich die Option zum Batch-Kodieren, wie aus yform_geo früher bekannt?

**Comment by skerbis** [comment]
gibt's nicht

**Comment by AWqxKAWERbXo** [comment]
Wäre super für die initiale Codierung.

**Comment by NGWNGW** [comment]
mit #15 erledigt
